openapi: 3.0.1
info:
  title: EncryptAndDecryptAPI
  description: API Definition of EncryptAndDecryptAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/encrypt-decrypt-api
paths:
  /:
    post:
      responses:
        default:
          description: Default response
